services:
  postgres:
    image: postgres:18-alpine

    environment:
      POSTGRES_USER: shopflow
      POSTGRES_PASSWORD: shopflow
      POSTGRES_DB: shopflow

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql

    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U shopflow -d shopflow"
        ]
      interval: 5s
      timeout: 5s
      retries: 5


  api:
    build:
      context: .
      dockerfile: apps/api/Dockerfile

    environment:
      PORT: 4000
      DATABASE_URL: postgresql://shopflow:shopflow@postgres:5432/shopflow

    ports:
      - "4000:4000"

    depends_on:
      postgres:
        condition: service_healthy


  web:
    build:
      context: .
      dockerfile: apps/web/Dockerfile

      args:
        NEXT_PUBLIC_API_URL: http://localhost:4000

    ports:
      - "3000:3000"


volumes:
  postgres_data: