sonar.projectName=ShopFlow

sonar.organization=maheshnd
sonar.projectKey=maheshnd_shopflow

sonar.sourceEncoding=UTF-8

sonar.sources=apps/api/src,apps/web/app,apps/web/features,apps/web/lib,packages/contracts/src,packages/ui/src

sonar.exclusions=\
**/*.test.ts,\
**/*.test.tsx,\
**/*.integration.test.ts,\
**/*.stories.ts,\
**/*.stories.tsx,\
**/node_modules/**,\
**/dist/**,\
**/.next/**,\
**/coverage/**,\
**/storybook-static/**

sonar.javascript.lcov.reportPaths=apps/web/coverage/lcov.info,apps/api/coverage/lcov.info